runtime: nodejs12
env: standard
# it is quite useles, because it works only for browser and the standard environement
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301